version: '3.8'

services:
  frontend:
    build:
      context: ./ui
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./ui:/app
    depends_on:
      - backend
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8080

  backend:
    build:
      context: ./api
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgres://postgres:password@db:5432/itemsdb?sslmode=disable

  db:
    image: postgres:13
    environment:
      POSTGRES_DB: itemsdb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

volumes:
  postgres_data: